[package]
name = "sort-visualizer"
version = "0.1.0"
authors = ["Asterisk007 <spykid1998@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8"
raylib = "3.7.0"

[features]
